language: php

php:
  - 5.6

install: composer install

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

script: make ci

branches:
  only:
    - php-56

notifications:
  email:
    on_success: never
